import os
import time
from datetime import datetime, timedelta
from html import escape
from zoneinfo import ZoneInfo

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st

from utils import (
    GLOBAL_PREDICTION_NAME,
    PARK_SETTINGS,
    auto_collect_prediction_context,
    auto_save_context_data,
    auto_fetch_dpa_if_needed,
    connect_db,
    clear_dpa_sellouts,
    fetch_ticket_prices,
    fetch_urtrip_dpa_sellouts,
    fetch_wait_times,
    get_calendar_bonus,
    get_crowd_index,
    get_current_stats,
    get_data_quality_report,
    get_dpa_score,
    get_feedback_error,
    get_forecast_weather_for_date,
    get_level,
    format_crowd_index,
    make_x_post_summary,
    get_next_feature_plan,
    get_attraction_status_summary,
    get_event_bonus,
    get_park_hours_bonus,
    get_today_park_hours,
    is_park_open_now,
    get_prediction_accuracy_report,
    get_prediction_alerts,
    get_prediction_confidence,
    get_area_crowd_map,
    get_all_attraction_crowd_stats,
    get_major_attraction_crowd_stats,
    get_crowd_index_from_major_attractions,
    get_actual_wait_series_for_today,
    get_attraction_prediction_confidence,
    get_attractions_by_theme_port,
    is_mojibake_text,
    merge_prediction_and_actual_series,
    safe_display_text,
    get_emptying_candidates,
    get_guest_action_plan,
    get_prediction_risk_diagnosis,
    get_show_wait_insights,
    load_show_schedules,
    load_show_wait_context,
    save_show_wait_context,
    get_historical_crowd_rank,
    get_prediction_gap_summary,
    get_wait_trend,
    get_ticket_price_from_castel,
    get_today_stats,
    get_valid_open_df,
    get_weather,
    get_weather_score,
    get_crowd_index_for_park,
    get_prediction_crowd_stats,
    build_time_slots,
    build_optimal_route_plan,
    format_route_plan_cards,
    load_daily_crowd_predictions,
    load_data_fetch_logs,
    load_dpa_fetch_logs,
    load_dpa_sellouts,
    load_attraction_status_snapshots,
    load_event_signals,
    load_park_hours,
    load_ticket_price_snapshots,
    load_weather_snapshots,
    log_dpa_fetch,
    load_history,
    load_prediction_history,
    make_major_average_prediction,
    make_locked_week_forecast as build_week_forecast,
    make_action_advice,
    predict_crowd_index_for_date,
    predict_dpa_sellout_time,
    predict_wait_times_for_date,
    save_daily_crowd_prediction,
    save_dpa_sellout,
    save_dpa_sellout_rows,
    save_attraction_status_snapshots,
    predict_dpa_risk,
    save_prediction_rows,
    save_wait_times,
    import_disneyreal_history,
    load_historical_import_logs,
    update_daily_crowd_feedback,
    update_prediction_feedback,
